### PR TITLE
add p2 python

### PR DESCRIPTION
**Pull request by wangzhao0217**
- **add p2/index.qmd**
- **Update DESCRIPTION for p2**
- **add python code**

### CODE REVIEW

**Review by Robinlovelace — CHANGES_REQUESTED** [review]
Can you remove the cache, and ensure tests pass Zhao? Overall, looking good.

**Comment by Robinlovelace** [comment]
Note: to get the latest changes from the `main` branch you can do the following:

```
git pull
git merge main
git push
```

**Comment by wangzhao0217** [comment]
> git push

Done, thanks for tip!

**Comment by Robinlovelace** [comment]
@wangzhao0217 I've had a look at the logs and it seems `jupyter-cache` is needed.

**Comment by Robinlovelace** [comment]
Logs can be found here: https://github.com/ITSLeeds/TDStests/actions/runs/11570835051/job/32207434073

**Comment by Robinlovelace** [comment]
See here and in the other workflow.yml file where we can install additional pkgs: 

https://github.com/ITSLeeds/TDStests/blob/ecebfa805057693ba1e06bdb7b49468c47488118/.github/workflows/pr.yml#L34

Should we add a requirements.txt file?

**Comment by Robinlovelace** [comment]
Before merging we need:

- [ ] the bits in the `{r, ...}` tags moved to Quarto-style tags, like `#| eval: false` replacing `{r, eval=FALSE}`
- [ ] Tabsets showing R and Python side-by-side
- [ ] Bonus: set eval: true in the global execution options in the yaml header

**Pull request merged**
